[phases.setup]
nixPkgs = [
  "nodejs_20",
  "npm-9_x",
  "openssl",
  "python311",
  "gcc",
  "gnumake",
  "pkg-config",
  "systemd"
]

[variables]
LIBUSB_CFLAGS = "-DNO_UDEV"

[phases.install]
cmds = ["cd apps/backend && npm install"]

[phases.build]
cmds = ["cd apps/backend && npm run build"]

[start]
cmd = "cd apps/backend && npm start"
